# Generated by Django 4.0.5 on 2023-06-29 09:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_boleta_fecentrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fecEntrega',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 9, 26, 47, 760847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
